# _config.yml

# required, replace with your own information -----
title: Saif Masoud's Portfolia
author: Saif Masoud
description: > 
  This is my portfolio showcasing a few personal projects.
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
#---------------------------------------------------

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

